In [64]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow
from tensorflow import keras
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

### Churn Model Predicton
- This is a project about how many coustomer bank will loss.
- Here we abserve some parameter(Gender, Tenure, Balance, NumofProducts, HasCECard, IsActiveMember, EstimatedSalary) and create model with the help of Tensorfow 

In [65]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [67]:
df.duplicated().sum()

0

In [68]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [69]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [70]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [71]:
df.drop(columns=['RowNumber', 'CustomerId', 'Surname'], inplace=True)

In [72]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [73]:
df = pd.get_dummies(df, columns=['Geography', 'Gender'], drop_first= True)

In [74]:
X = df.drop(columns=['Exited'])
y = df['Exited']

In [75]:
X_train , X_test , y_train , y_test = train_test_split(X, y , test_size= 0.2 , random_state= 42)

In [76]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [77]:
X_test_scaled

array([[-0.57749609, -0.6557859 , -0.69539349, ...,  1.72572313,
        -0.57638802,  0.91324755],
       [-0.29729735,  0.3900109 , -1.38944225, ..., -0.57946723,
        -0.57638802,  0.91324755],
       [-0.52560743,  0.48508334, -0.3483691 , ..., -0.57946723,
         1.73494238, -1.09499335],
       ...,
       [ 0.81311987,  0.77030065,  0.69270405, ..., -0.57946723,
        -0.57638802, -1.09499335],
       [ 0.41876609, -0.94100321, -0.3483691 , ..., -0.57946723,
        -0.57638802,  0.91324755],
       [-0.24540869,  0.00972116, -1.38944225, ...,  1.72572313,
        -0.57638802,  0.91324755]])

In [78]:
from tensorflow.keras import Sequential
model = Sequential()
model.add(Dense(3, activation = 'sigmoid', input_dim =11))
model.add(Dense(1, activation = 'sigmoid'))

In [79]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 3)                 36        
                                                                 
 dense_5 (Dense)             (None, 1)                 4         
                                                                 
Total params: 40
Trainable params: 40
Non-trainable params: 0
_________________________________________________________________


In [80]:
model.compile(loss= 'binary_crossentropy', optimizer= 'Adam')

In [81]:
model.fit(X_train_scaled , y_train, epochs=100)

Epoch 1/100


250/250 [==============================] - 1s 975us/step - loss: 0.7497
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5816
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5108
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4798
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4639
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4538
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4465
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4410
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4369
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4338
Epoch 11/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4312
Epoch 12/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4291
Epoch 13/100
250/250 [=

In [82]:
model.layers[0].get_weights()

[array([[ 0.02065931,  0.03244542, -0.20147173],
        [-0.44126996,  0.01582959,  3.518297  ],
        [-0.14898771,  0.08821879,  0.05476801],
        [-0.73647743, -0.70025474,  0.15068935],
        [-3.8597593 , -1.947813  ,  0.5909372 ],
        [-0.08519388,  0.10644048,  0.19096428],
        [-1.0348841 ,  0.5909991 ,  0.4534387 ],
        [ 0.1379597 , -0.05633246, -0.17756058],
        [ 0.7720006 ,  0.07256031,  0.16273731],
        [-0.05567679, -0.17517594, -0.05156217],
        [-0.2366915 ,  0.3189844 , -0.11315913]], dtype=float32),
 array([-2.0161645 ,  2.6642513 , -0.55099297], dtype=float32)]

In [83]:
model.layers[0].get_weights()

[array([[ 0.02065931,  0.03244542, -0.20147173],
        [-0.44126996,  0.01582959,  3.518297  ],
        [-0.14898771,  0.08821879,  0.05476801],
        [-0.73647743, -0.70025474,  0.15068935],
        [-3.8597593 , -1.947813  ,  0.5909372 ],
        [-0.08519388,  0.10644048,  0.19096428],
        [-1.0348841 ,  0.5909991 ,  0.4534387 ],
        [ 0.1379597 , -0.05633246, -0.17756058],
        [ 0.7720006 ,  0.07256031,  0.16273731],
        [-0.05567679, -0.17517594, -0.05156217],
        [-0.2366915 ,  0.3189844 , -0.11315913]], dtype=float32),
 array([-2.0161645 ,  2.6642513 , -0.55099297], dtype=float32)]

In [84]:
y_log =model.predict(X_test_scaled)

63/63 [==============================] - 0s 1ms/step


In [85]:
y_pred = np.where (y_log > 0.5, 1,0)

In [86]:
from sklearn.metrics import accuracy_score

In [87]:
accuracy_score(y_test, y_pred)

0.86